### ISSUE TITLE
Compile error 

### ISSUE THREAD

**Issue by rafaelSorel** [superna9999/meson_gx_mali_450#2]
Hello I 'am getting this error when try to compile the mali driver r6p1 :
`
/root/project/meson_gx_mali_450/driver/src/devicedrv/mali/platform/meson/meson.c:69:32: fatal error: linux/clk/clk-conf.h: No such file or directory
`

I 'am using linux kernel for amlogix S905X board:
https://github.com/150balbes/Amlogic_s905-kernel/tree/armbian

Kernel version 3.14.29

Thanks for help

**Comment by superna9999** [comment]
Sorry, this code is only for the mainline linux, not the amlogic 3.14 kernel
